### ISSUE TITLE
 Замечания

### ISSUE THREAD

**Issue by dzheltkov** [artiebears13/dot_position#1]
1) Первое задание зачтено.

2) Второе задание зачтено.

3) Нет обработки ошибок ввода из файла, поэтому третье пока не зачтено. Кроме того, для того, чтобы третье задание было зачтено, необходимо использовать перечислимый тип (или для обработки ошибок, или можно для возвращаемого результата функции - вне / внутри / на стороне).

4) Сохранять углы в вектор нет смысла, вместо этого их можно сразу обрабатывать.

**Comment by artiebears13** [comment]
Добрый день! Внес исправления

**Comment by dzheltkov** [comment]
Добрый день!

Вы пока так и не добавили обработку ошибок в файле.
Обработка ошибок ввода из командной строки у вас, в целом, уже была (не хватало лишть проверки того, что аргументов достаточно), можно было оставить и её (только добавить проверку числа аргументов и более детализировано сообщать об ошибках). Более того, сейчас у вас при некорректно введенных аргументах запуска программа выведет уведомление об ошибке, но продолжит работу, что неправильно.

**Comment by artiebears13** [comment]
Добрый день! Дописал проверку файла и исправил продолжение работы при уведомлении об ошибке

**Comment by dzheltkov** [comment]
Хорошо, третье задание затчено.
